version: 2
updates:
  # Version updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    rebase-strategy: "auto"
    versioning-strategy: "auto"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Version updates for Cargo packages
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    rebase-strategy: "auto"
    groups:
      cargo-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(actions)"
    groups:
      github-actions:
        patterns:
          - "*"
